-- ============================================================
-- 0046_support_chat.sql
-- Чат «Поддержка Kolibel» — системная беседа у каждого аккаунта.
--   • conversations.kind ('dm'|'support') — метка системной беседы;
--   • системные сообщения (приветствие/бампы) — sender_id = NULL (левая сторона);
--   • беседа read-only для пользователя: писать/править/удалять сообщения нельзя
--     (всё пишется security-definer-RPC), а сама беседа не удаляется;
--   • reports.seq — человекочитаемый № жалобы;
--   • RPC ensure_support_conversation() — лениво создаёт беседу + приветствие;
--   • RPC submit_report(...) — атомарно пишет жалобу + карточку в support-беседу;
--   • RPC get_my_report(...) — «живая» карточка: жалоба + ветка ответов модерации.
-- Применить: Supabase Dashboard → SQL Editor → вставить → Run. Идемпотентна.
-- ============================================================

-- 1) Метка системной беседы + системные сообщения ------------------------
alter table public.conversations
  add column if not exists kind text not null default 'dm';
alter table public.conversations drop constraint if exists conversations_kind_check;
alter table public.conversations add constraint conversations_kind_check
  check (kind in ('dm', 'support'));

-- Системные сообщения поддержки не имеют отправителя-профиля (sender_id = NULL).
alter table public.messages alter column sender_id drop not null;
alter table public.messages add column if not exists system boolean not null default false;

-- 2) Человекочитаемый № жалобы (существующие строки получают значения) -----
alter table public.reports add column if not exists seq bigint generated by default as identity;

-- 3) Хелпер «это беседа поддержки?» (security definer — обход RLS без рекурсии) -
create or replace function public.is_support_conversation(p_conversation_id uuid)
returns boolean
language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.conversations
    where id = p_conversation_id and kind = 'support'
  );
$$;

-- 4) Read-only для пользователя: нельзя писать/править/удалять в support-беседе.
--    (Приветствие/карточки/ответы пишутся security-definer-RPC — они обходят RLS.)
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated
  with check (
    sender_id = auth.uid()
    and public.is_conversation_participant(conversation_id)
    and not public.is_support_conversation(conversation_id)
  );

drop policy if exists messages_update_own on public.messages;
create policy messages_update_own on public.messages for update to authenticated
  using (sender_id = auth.uid() and not public.is_support_conversation(conversation_id))
  with check (sender_id = auth.uid() and not public.is_support_conversation(conversation_id));

drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own on public.messages for delete to authenticated
  using (sender_id = auth.uid() and not public.is_support_conversation(conversation_id));

-- 5) Беседу поддержки нельзя удалить (guard в существующем RPC из 0014) ------
create or replace function public.delete_conversation(p_conversation_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then
    raise exception 'Нет активной сессии';
  end if;
  if not public.is_conversation_participant(p_conversation_id) then
    raise exception 'Нет доступа к беседе';
  end if;
  if public.is_support_conversation(p_conversation_id) then
    raise exception 'Беседу поддержки удалить нельзя';
  end if;
  delete from public.conversations where id = p_conversation_id;
end;
$$;

-- 6) Ленивое создание беседы поддержки + приветствие -----------------------
create or replace function public.ensure_support_conversation()
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_me   uuid := auth.uid();
  v_conv uuid;
begin
  if v_me is null then
    raise exception 'Нет активной сессии';
  end if;

  select c.id into v_conv
  from public.conversations c
  join public.conversation_participants p
    on p.conversation_id = c.id and p.user_id = v_me
  where c.kind = 'support'
  limit 1;

  if v_conv is not null then
    return v_conv;
  end if;

  insert into public.conversations (kind) values ('support') returning id into v_conv;
  insert into public.conversation_participants (conversation_id, user_id) values (v_conv, v_me);

  insert into public.messages (conversation_id, sender_id, body, system)
  values (
    v_conv, null,
    'Здравствуйте! Это официальный чат «Поддержка Kolibel». ' ||
    'Здесь будут храниться ваши жалобы и ответы модерации: как только вы отправите жалобу, ' ||
    'в этом чате появится её карточка, а все решения по ней придут прямо в неё. ' ||
    'Писать в этот чат не нужно — он служит для отслеживания ваших обращений.',
    true
  );

  return v_conv;
end;
$$;

-- 7) Подача жалобы + карточка в чат поддержки (атомарно) -------------------
--    p_evidence — jsonb-массив публичных URL уже загруженных скриншотов.
create or replace function public.submit_report(
  p_target_type text,
  p_target_id   uuid,
  p_category    text,
  p_description text,
  p_evidence    jsonb default '[]'::jsonb
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_me     uuid := auth.uid();
  v_report uuid;
  v_seq    bigint;
  v_conv   uuid;
begin
  if v_me is null then
    raise exception 'Нужно войти, чтобы отправить жалобу';
  end if;
  if p_target_type not in ('user', 'company', 'post', 'comment', 'vacancy') then
    raise exception 'Некорректный тип цели';
  end if;

  insert into public.reports (reporter_id, target_type, target_id, category, description, evidence)
  values (v_me, p_target_type, p_target_id, coalesce(p_category, ''),
          coalesce(p_description, ''), coalesce(p_evidence, '[]'::jsonb))
  returning id, seq into v_report, v_seq;

  v_conv := public.ensure_support_conversation();

  -- Карточка жалобы — сообщение ОТ пользователя (правая сторона). Раскрывается в UI.
  insert into public.messages (conversation_id, sender_id, body, attach)
  values (
    v_conv, v_me, '',
    jsonb_build_object(
      'kind',           'report',
      'title',          'Жалоба №' || v_seq,
      'reportId',       v_report::text,
      'reportSeq',      v_seq,
      'reportCategory', coalesce(p_category, ''),
      'reportStatus',   'new'
    )
  );

  return v_report;
end;
$$;

-- 8) «Живая» карточка: жалоба + её ветка ответов модерации (только автору) --
create or replace function public.get_my_report(p_report_id uuid)
returns jsonb
language sql security definer stable set search_path = public as $$
  select jsonb_build_object(
    'seq',         r.seq,
    'category',    r.category,
    'description', r.description,
    'status',      r.status,
    'createdAt',   extract(epoch from r.created_at) * 1000,
    'evidence',    coalesce(r.evidence, '[]'::jsonb),
    'responses',   coalesce((
      select jsonb_agg(jsonb_build_object(
        'resolution', mr.resolution,
        'reason',     mr.reason,
        'comment',    mr.comment,
        'createdAt',  extract(epoch from mr.created_at) * 1000
      ) order by mr.created_at)
      from public.moderation_responses mr
      where mr.report_id = r.id
        and mr.user_id = auth.uid()
        and mr.kind = 'report_result'
    ), '[]'::jsonb)
  )
  from public.reports r
  where r.id = p_report_id
    and r.reporter_id = auth.uid();
$$;
